/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package br.com.ifba.atividade08.view;

/**
 *
 * @author fabricio
 */
public class Tela extends javax.swing.JFrame {

    /**
     * Creates new form Tela
     */
    public Tela() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        //Criar contas 
        ContaBanco c1 = new ContaBanco(1111, "Andeson Reis");
        ContaBanco c2 = new ContaBanco(2222, "Sudão de João Dourado");

        //Abrir Contas 
        c1.abrirConta("cc"); // Corrente Saldo inicial R$ 50
        c2.abrirConta("cp"); // Poupança  Saldo inicial R$ 150

        //Depósitos e Saques
        c1.depositar(300); 
        c2.depositar(500); 
        c1.sacar(380);     
        c1.sacar(150);     

        //Pagar Mensalidade 
        c1.pagarMensal(); // c1(cc) paga R$ 12,00. Saldo c1: 200 - 12 = 188,00
        c2.pagarMensal(); // c2(cp) paga R$ 20,00. Saldo c2: 650 - 20 = 630,00

       
        c1.fecharConta(); 

        
        c2.sacar(630);    
        c2.fecharConta(); 

        // Exibindo status final 
        System.out.println("\n--- STATUS FINAIS ---");
        System.out.println("Conta de Andeson Reis | Saldo: R$ " + c1.getSaldo() + " | Status: " + (c1.getStatus() == 1 ? "ABERTA" : "FECHADA"));
        System.out.println("Conta de Sudão de João Dourado | Saldo: R$ " + c2.getSaldo() + " | Status: " + (c2.getStatus() == 1 ? "ABERTA" : "FECHADA"));
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Tela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Tela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Tela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Tela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Tela().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
