/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package br.com.atividade10.view;

/**
 *
 * @author fabricio
 */
public class TelaPagamentos extends javax.swing.JFrame {

    /**
     * Creates new form TelaPagamentos
     */
    public TelaPagamentos() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        spnTipoPagamentos = new javax.swing.JSpinner();
        txtvalorPagamentos = new javax.swing.JTextField();
        lblPagamentos = new javax.swing.JLabel();
        btnCalcularValor = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        spnTipoPagamentos.setModel(new javax.swing.SpinnerListModel(new String[] {"Pagamento em Dinheiro", "Pagamento em Cartao", "Pagamento em Pix"}));

        txtvalorPagamentos.setText("0,0");
        txtvalorPagamentos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtvalorPagamentosActionPerformed(evt);
            }
        });

        lblPagamentos.setText("Informe o Valor do pagamentos");

        btnCalcularValor.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/ifba/atividade10/image/calculadora(2).png"))); // NOI18N
        btnCalcularValor.setText("Calcular Valor");
        btnCalcularValor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCalcularValorActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addComponent(spnTipoPagamentos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnCalcularValor, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblPagamentos))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtvalorPagamentos, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(85, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(96, 96, 96)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(spnTipoPagamentos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblPagamentos)
                    .addComponent(txtvalorPagamentos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(31, 31, 31)
                .addComponent(btnCalcularValor, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(40, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtvalorPagamentosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtvalorPagamentosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtvalorPagamentosActionPerformed

    private void btnCalcularValorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCalcularValorActionPerformed
        // pega o valor da compra
    double valorCompra = 0.0;
    try {
        String valorStr = txtvalorPagamentos.getText().replace(",", ".");
        valorCompra = Double.parseDouble(valorStr);
    } catch (NumberFormatException e) {
        javax.swing.JOptionPane.showMessageDialog(this, "Erro: Valor de compra inválido.", "Erro de Entrada", javax.swing.JOptionPane.ERROR_MESSAGE);
        return;
    }

    // obtem o tipo de pagamento selecionado
    String tipoPagamento = (String) spnTipoPagamentos.getValue();
    Pagamento pagamento = null;

    switch (tipoPagamento) {
        case "Pagamento em Dinheiro":
            pagamento = new PagamentoDinheiro(valorCompra);
            break;
        case "Pagamento em Cartao":
            pagamento = new PagamentoCartao(valorCompra);
            break;
        case "Pagamento em Pix":
            pagamento = new PagamentoPix(valorCompra);
            break;
        default:
            javax.swing.JOptionPane.showMessageDialog(this, "Tipo de pagamento não suportado.", "Erro", javax.swing.JOptionPane.ERROR_MESSAGE);
            return;
    }

    // ostrar o valor final e o recibo 
    if (pagamento != null) {
        // double valorFinal = pagamento.calcularTotal(); 
        pagamento.imprimirRecibo(); // mostra o recibo com o valor final
    }

    }//GEN-LAST:event_btnCalcularValorActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaPagamentos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaPagamentos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaPagamentos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaPagamentos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaPagamentos().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCalcularValor;
    private javax.swing.JLabel lblPagamentos;
    private javax.swing.JSpinner spnTipoPagamentos;
    private javax.swing.JTextField txtvalorPagamentos;
    // End of variables declaration//GEN-END:variables
}
