/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package br.com.ifba.atividade06.view;

import java.util.Arrays;
import javax.swing.DefaultListModel;

/**
 *
 * @author fabricio
 */
public class TelaVetor extends javax.swing.JFrame {
    
    private final int [] vetor = new int[10];
    private int quantidade = 0;
    
    
    /**
     * Creates new form TelaVetor
     */
    public TelaVetor() {
        initComponents();
        
        DefaultListModel lista = new DefaultListModel();
        
        jList2.setModel(lista);
        
        txtQuantidadeNum.setText(String.valueOf(quantidade));
        
        
    }
    
    private void atualizaLista() {
        this.lista.clear(); // Deve usar o 'this.lista' que é o DefaultListModel real.
        for (int i = 0; i < quantidade; i++) {
            this.lista.addElement("Índice " + i + ": " + vetor[i]);
        }

        // ADICIONADO: Atualiza o campo de texto da quantidade.
        txtQuantidadeNum.setText(String.valueOf(quantidade));
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList<>();
        pnlTelaVetor = new javax.swing.JPanel();
        sldNumeros = new javax.swing.JSpinner();
        bntAdicionar = new javax.swing.JButton();
        bntRemover = new javax.swing.JButton();
        bntOrdenar = new javax.swing.JButton();
        TxtVetor = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        jList2 = new javax.swing.JList<>();
        txtQuantidadeNum = new javax.swing.JTextField();

        jList1.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane1.setViewportView(jList1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        pnlTelaVetor.setBackground(new java.awt.Color(204, 255, 255));

        sldNumeros.setModel(new javax.swing.SpinnerNumberModel(0, -10, 10, 1));

        bntAdicionar.setText("Adicionar");
        bntAdicionar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bntAdicionarActionPerformed(evt);
            }
        });

        bntRemover.setText("Remover");
        bntRemover.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bntRemoverActionPerformed(evt);
            }
        });

        bntOrdenar.setText("Ordenar");
        bntOrdenar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bntOrdenarActionPerformed(evt);
            }
        });

        TxtVetor.setText("Vetor");
        TxtVetor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TxtVetorActionPerformed(evt);
            }
        });

        jList2.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane2.setViewportView(jList2);

        txtQuantidadeNum.setText("0");

        javax.swing.GroupLayout pnlTelaVetorLayout = new javax.swing.GroupLayout(pnlTelaVetor);
        pnlTelaVetor.setLayout(pnlTelaVetorLayout);
        pnlTelaVetorLayout.setHorizontalGroup(
            pnlTelaVetorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlTelaVetorLayout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addComponent(sldNumeros, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32)
                .addGroup(pnlTelaVetorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(bntRemover, javax.swing.GroupLayout.DEFAULT_SIZE, 109, Short.MAX_VALUE)
                    .addComponent(bntAdicionar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(bntOrdenar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(37, 37, 37)
                .addGroup(pnlTelaVetorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 227, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, pnlTelaVetorLayout.createSequentialGroup()
                        .addComponent(TxtVetor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(txtQuantidadeNum, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(32, Short.MAX_VALUE))
        );
        pnlTelaVetorLayout.setVerticalGroup(
            pnlTelaVetorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlTelaVetorLayout.createSequentialGroup()
                .addGap(61, 61, 61)
                .addGroup(pnlTelaVetorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtQuantidadeNum, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TxtVetor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(pnlTelaVetorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlTelaVetorLayout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addComponent(bntAdicionar, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(36, 36, 36)
                        .addGroup(pnlTelaVetorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(bntRemover, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(sldNumeros, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(34, 34, 34)
                        .addComponent(bntOrdenar, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnlTelaVetorLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 298, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(30, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlTelaVetor, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlTelaVetor, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void TxtVetorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxtVetorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TxtVetorActionPerformed

    private void bntAdicionarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bntAdicionarActionPerformed
        // TODO add your handling code here:
        if (quantidade < vetor.length){
            // 2. Obter o valor do JSpinner
            int novoNumero = (int) sldNumeros.getValue();

            // 3. Adicionar o número e incrementar o contador
            vetor[quantidade] = novoNumero;
            quantidade++;

            // 4. Atualizar a lista na tela
            atualizaLista();
        }else{
            javax.swing.JOptionPane.showMessageDialog(this, "Vetor cheio! Remova um elemento antes de adicionar.");
        }
    
    }//GEN-LAST:event_bntAdicionarActionPerformed

    private void bntRemoverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bntRemoverActionPerformed
        // TODO add your handling code here:
        int selecionado = jList2.getSelectedIndex();

        // 2. Verificar se um item válido foi selecionado
        if (selecionado != -1 && quantidade > 0) {

            // 3. Remover: mover os elementos seguintes para a esquerda
            for (int i = selecionado; i < quantidade - 1; i++){
                vetor[i] = vetor[i + 1];
            }

            // 4. Decrementar o contador
            quantidade--;

            // 5. Atualizar a lista na tela
            atualizaLista();
        }else if(quantidade > 0){
            javax.swing.JOptionPane.showMessageDialog(this, "Selecione um item na lista para remover.");
        }else{
            javax.swing.JOptionPane.showMessageDialog(this, "O vetor está vazio.");
        }
    }//GEN-LAST:event_bntRemoverActionPerformed

    private void bntOrdenarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bntOrdenarActionPerformed
        // TODO add your handling code here:
        if (quantidade > 1) {
            // 2. Ordenar APENAS a porção do vetor que contém dados (do índice 0 até 'quantidade')
            Arrays.sort(vetor, 0, quantidade);

            // 3. Atualizar a lista na tela
            atualizaLista();
        } else if (quantidade > 0) {
            javax.swing.JOptionPane.showMessageDialog(this, "O vetor tem apenas um elemento. Não há o que ordenar.");
        } else {
            javax.swing.JOptionPane.showMessageDialog(this, "O vetor está vazio.");
        }
    }//GEN-LAST:event_bntOrdenarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaVetor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaVetor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaVetor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaVetor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaVetor().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField TxtVetor;
    private javax.swing.JButton bntAdicionar;
    private javax.swing.JButton bntOrdenar;
    private javax.swing.JButton bntRemover;
    private javax.swing.JList<String> jList1;
    private javax.swing.JList<String> jList2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JPanel pnlTelaVetor;
    private javax.swing.JSpinner sldNumeros;
    private javax.swing.JTextField txtQuantidadeNum;
    // End of variables declaration//GEN-END:variables

    private class lista {

        private static void clear() {
            throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
        }

        private static void addElement(String string) {
            throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
        }

        public lista() {
        }
    }
}
