/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package br.com.ifba.atividade03.view;

/**
 *
 * @author  fabricio
 */
public class Tela  extends javax.swing.JFrame {

    /**
     * Creates new form Tela
     */
    public Tela() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        pnlContainer1 = new javax.swing.JPanel();
        pnlContainerTitulo = new javax.swing.JPanel();
        lblTitulo = new javax.swing.JLabel();
        pnlContainerOpcoes = new javax.swing.JPanel();
        lblIdade = new javax.swing.JLabel();
        spnDia = new javax.swing.JSpinner();
        spnMes = new javax.swing.JSpinner();
        spnAno = new javax.swing.JSpinner();
        lblDia = new javax.swing.JLabel();
        lblMes = new javax.swing.JLabel();
        lblAno = new javax.swing.JLabel();
        pnlContainerButton = new javax.swing.JPanel();
        bntCalcular = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        pnlContainerResultado = new javax.swing.JPanel();
        lblResutaldoIdade = new javax.swing.JLabel();
        txtResultado = new javax.swing.JTextField();

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        pnlContainer1.setBackground(new java.awt.Color(255, 255, 255));
        pnlContainer1.setBorder(new javax.swing.border.MatteBorder(null));

        pnlContainerTitulo.setBackground(new java.awt.Color(255, 255, 255));
        pnlContainerTitulo.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 102, 102)));

        lblTitulo.setFont(new java.awt.Font("Liberation Sans", 0, 18)); // NOI18N
        lblTitulo.setText("Calculadora de idade");

        javax.swing.GroupLayout pnlContainerTituloLayout = new javax.swing.GroupLayout(pnlContainerTitulo);
        pnlContainerTitulo.setLayout(pnlContainerTituloLayout);
        pnlContainerTituloLayout.setHorizontalGroup(
            pnlContainerTituloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlContainerTituloLayout.createSequentialGroup()
                .addGap(206, 206, 206)
                .addComponent(lblTitulo)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnlContainerTituloLayout.setVerticalGroup(
            pnlContainerTituloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblTitulo, javax.swing.GroupLayout.DEFAULT_SIZE, 35, Short.MAX_VALUE)
        );

        pnlContainerOpcoes.setBackground(new java.awt.Color(255, 255, 255));
        pnlContainerOpcoes.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 102, 102)));

        lblIdade.setFont(new java.awt.Font("Liberation Sans", 0, 18)); // NOI18N
        lblIdade.setText("Informe sua data de nascimento");

        spnDia.setModel(new javax.swing.SpinnerNumberModel(1, 1, 31, 1));

        spnMes.setModel(new javax.swing.SpinnerNumberModel(1, 1, 12, 1));

        spnAno.setModel(new javax.swing.SpinnerNumberModel(2000, 0, 2025, 1));

        lblDia.setFont(new java.awt.Font("Liberation Sans", 0, 17)); // NOI18N
        lblDia.setText("Dia");

        lblMes.setFont(new java.awt.Font("Liberation Sans", 0, 17)); // NOI18N
        lblMes.setText("Mes");

        lblAno.setFont(new java.awt.Font("Liberation Sans", 0, 17)); // NOI18N
        lblAno.setText("Ano");

        javax.swing.GroupLayout pnlContainerOpcoesLayout = new javax.swing.GroupLayout(pnlContainerOpcoes);
        pnlContainerOpcoes.setLayout(pnlContainerOpcoesLayout);
        pnlContainerOpcoesLayout.setHorizontalGroup(
            pnlContainerOpcoesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlContainerOpcoesLayout.createSequentialGroup()
                .addGroup(pnlContainerOpcoesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlContainerOpcoesLayout.createSequentialGroup()
                        .addGap(101, 101, 101)
                        .addComponent(spnDia, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(48, 48, 48)
                        .addComponent(spnMes, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(45, 45, 45)
                        .addComponent(spnAno, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnlContainerOpcoesLayout.createSequentialGroup()
                        .addGap(127, 127, 127)
                        .addGroup(pnlContainerOpcoesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lblIdade, javax.swing.GroupLayout.PREFERRED_SIZE, 266, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(pnlContainerOpcoesLayout.createSequentialGroup()
                                .addComponent(lblDia)
                                .addGap(106, 106, 106)
                                .addComponent(lblMes)
                                .addGap(116, 116, 116)
                                .addComponent(lblAno)))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnlContainerOpcoesLayout.setVerticalGroup(
            pnlContainerOpcoesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlContainerOpcoesLayout.createSequentialGroup()
                .addGroup(pnlContainerOpcoesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlContainerOpcoesLayout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(pnlContainerOpcoesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblDia)
                            .addComponent(lblMes))
                        .addGap(18, 18, 18))
                    .addGroup(pnlContainerOpcoesLayout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addComponent(lblIdade)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lblAno)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 22, Short.MAX_VALUE)))
                .addGroup(pnlContainerOpcoesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlContainerOpcoesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(spnMes, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(spnAno, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(spnDia, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(15, 15, 15))
        );

        pnlContainerButton.setBackground(new java.awt.Color(255, 255, 255));
        pnlContainerButton.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 102, 102)));

        bntCalcular.setBackground(new java.awt.Color(204, 204, 204));
        bntCalcular.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/ifba/atividade03/images/calculadora(2).png"))); // NOI18N
        bntCalcular.setText("Calcular");
        bntCalcular.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bntCalcularActionPerformed(evt);
            }
        });

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/ifba/atividade03/images/grupo-de-idade(3).png"))); // NOI18N

        javax.swing.GroupLayout pnlContainerButtonLayout = new javax.swing.GroupLayout(pnlContainerButton);
        pnlContainerButton.setLayout(pnlContainerButtonLayout);
        pnlContainerButtonLayout.setHorizontalGroup(
            pnlContainerButtonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlContainerButtonLayout.createSequentialGroup()
                .addGap(82, 82, 82)
                .addComponent(bntCalcular, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(78, 78, 78)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnlContainerButtonLayout.setVerticalGroup(
            pnlContainerButtonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlContainerButtonLayout.createSequentialGroup()
                .addGroup(pnlContainerButtonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlContainerButtonLayout.createSequentialGroup()
                        .addGap(17, 17, 17)
                        .addComponent(jLabel1))
                    .addGroup(pnlContainerButtonLayout.createSequentialGroup()
                        .addGap(52, 52, 52)
                        .addComponent(bntCalcular, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(20, Short.MAX_VALUE))
        );

        pnlContainerResultado.setBackground(new java.awt.Color(255, 255, 255));
        pnlContainerResultado.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 102, 102)));

        lblResutaldoIdade.setFont(new java.awt.Font("Liberation Sans", 0, 18)); // NOI18N
        lblResutaldoIdade.setText("A sua idade é:");

        javax.swing.GroupLayout pnlContainerResultadoLayout = new javax.swing.GroupLayout(pnlContainerResultado);
        pnlContainerResultado.setLayout(pnlContainerResultadoLayout);
        pnlContainerResultadoLayout.setHorizontalGroup(
            pnlContainerResultadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlContainerResultadoLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(lblResutaldoIdade, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtResultado, javax.swing.GroupLayout.PREFERRED_SIZE, 404, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(34, Short.MAX_VALUE))
        );
        pnlContainerResultadoLayout.setVerticalGroup(
            pnlContainerResultadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlContainerResultadoLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(pnlContainerResultadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblResutaldoIdade, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtResultado, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(14, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout pnlContainer1Layout = new javax.swing.GroupLayout(pnlContainer1);
        pnlContainer1.setLayout(pnlContainer1Layout);
        pnlContainer1Layout.setHorizontalGroup(
            pnlContainer1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlContainer1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlContainer1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pnlContainerTitulo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pnlContainerOpcoes, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pnlContainerButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pnlContainerResultado, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        pnlContainer1Layout.setVerticalGroup(
            pnlContainer1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlContainer1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pnlContainerTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(pnlContainerOpcoes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(pnlContainerButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(pnlContainerResultado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(29, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(pnlContainer1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(pnlContainer1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bntCalcularActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bntCalcularActionPerformed
        // TODO add your handling code here:
        
        // captura o dia, ano e mes selecionados nos spinner e converte para int
        int dia = (int) spnDia.getValue();
        int mes = (int) spnMes.getValue();
        int ano = (int) spnAno.getValue();

            try{
                // java.time.LocalData -> classe do pacote java time para data
                // Data de nascimento informada
                java.time.LocalDate nascimento = java.time.LocalDate.of(ano, mes, dia);
                
                
                // Data de hoje -> utiiza a data do sistema operacional da maquina
                java.time.LocalDate hoje = java.time.LocalDate.now();
                
                // verificação se a data informando pelo usuario estiver afrete da data de hoje ele retorna data invalida, e pede pra informa outra data
                if(nascimento.isAfter(hoje)){
                txtResultado.setText(" Data invalda!, informe outra data. ");
                return;
                }


                // Calcula a diferença java.time.period é java.timePeriod.between calcular a diferencia entre duas instancia de LocalTime e retorna o resultao em anos, meses e dias
                java.time.Period idade = java.time.Period.between(nascimento, hoje);

                // mosta o resultado
                txtResultado.setText(
                "Sua idade é: " + idade.getYears() + " anos, " + idade.getMonths() + " meses e " + idade.getDays() + " dias.");
                
            // Informa exceçẽos caso os valores dos spinners não formem uma data válida
            }catch (Exception e){
                txtResultado.setText(" Data invalida!");
                }
    }//GEN-LAST:event_bntCalcularActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Tela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Tela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Tela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Tela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Tela().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bntCalcular;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblAno;
    private javax.swing.JLabel lblDia;
    private javax.swing.JLabel lblIdade;
    private javax.swing.JLabel lblMes;
    private javax.swing.JLabel lblResutaldoIdade;
    private javax.swing.JLabel lblTitulo;
    private javax.swing.JPanel pnlContainer1;
    private javax.swing.JPanel pnlContainerButton;
    private javax.swing.JPanel pnlContainerOpcoes;
    private javax.swing.JPanel pnlContainerResultado;
    private javax.swing.JPanel pnlContainerTitulo;
    private javax.swing.JSpinner spnAno;
    private javax.swing.JSpinner spnDia;
    private javax.swing.JSpinner spnMes;
    private javax.swing.JTextField txtResultado;
    // End of variables declaration//GEN-END:variables
}

//test